Improve perf on large shops
PrestaShop/ps_crossselling pull request #25
Opened 2021-03-19 10:42 UTC by jf-viguier

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | On large shops, getting all commands of all time can be heavy. I limit to the 100 last orders containing the products.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | TBD
| How to test?  | N/A

2021-03-19 10:45 UTC, jf-viguier commented
phpstan error is not related to my pr, I've just changed an sql request "Error: Your lock file does not contain a compatible set of packages. Please run composer update."

2021-03-19 15:52 UTC, PierreRambaud commented on ps_crossselling.php
> +        ORDER BY date_add desc LIMIT 100';
Why not use: `LIMIT ' . (int) Configuration::get('CROSSSELLING_NBR')`?

2021-03-19 16:13 UTC, Progi1984 commented
@jf-viguier I will fix CI in #26

2021-03-19 17:28 UTC, jf-viguier commented on ps_crossselling.php
> +        ORDER BY date_add desc LIMIT 100';
@PierreRambaud CROSSSELLING_NBR is for the number of products, not the number of orders. Then there is an order by rand() in order not to show only the product of the last orders.

2021-03-22 13:58 UTC, PierreRambaud commented on ps_crossselling.php
> +        ORDER BY date_add desc LIMIT 100';
Hum, I understand. 
It could be interesting to have a bench to see if results are similar with or without this change, could you do that?

2021-03-22 18:09 UTC, jf-viguier commented on ps_crossselling.php
> +        ORDER BY date_add desc LIMIT 100';
@PierreRambaud 
The getOrderProducts method make two requests : 
- a first one to get all orders containing cart products
- a second huge request to get all ordered products of this set of orders : this second request will be faster with 100 orders than 100K or 1 million orders. This second request has a lot's of join.

Mr pr on the first request is there to get the second one faster. There is no need for a bench on this IMO.

Another point : getting orders of all time in a large and old shop will, maybe, suggest old products that are no more up to date like an iPhone 3 ;-) or out of stock for ever. By taking the last 100 orders we suggest recently ordered products.

If you're uncomfortable with the fixed 100 limit, we could use Configuration::get('CROSSSELLING_NBR')*50, WDYT ?

2021-03-23 08:44 UTC, Progi1984 commented
> @jf-viguier I will fix CI in #26

It's good. You can rebase.

2021-03-23 08:58 UTC, PierreRambaud commented on ps_crossselling.php
> +        ORDER BY date_add desc LIMIT 100';
Why not, at least it will try to retrieve orders based on the number of products we wanted to find :sweat_smile:

2021-03-23 09:52 UTC, jf-viguier commented on ps_crossselling.php
> +        ORDER BY date_add desc LIMIT 100';
@PierreRambaud done

2021-03-23 11:16 UTC, Progi1984 approved these changes

2021-03-24 08:33 UTC, matthieu-rolland approved these changes

2021-03-24 08:42 UTC, Progi1984 commented
@jf-viguier Could you give us a test case ?

2021-03-25 09:14 UTC, PierreRambaud approved these changes

2021-05-16 19:27 UTC, matks commented
> @jf-viguier Could you give us a test case ?

@jf-viguier friendly reminder 😉

2021-05-20 14:12 UTC, jf-viguier commented
Do you need a test case to see that a limit in a 1million order table is useful ?
For the record, the getOrderProducts method make two requests :
- a first one to get all orders containing cart products : this one is reduced by my pr
- a second huge request to get all ordered products of this set of orders : this second request will be faster with 1 million orders. This second request has a lot's of join.

2021-12-14 08:54 UTC, matks commented
Friendly reminder @jf-viguier 😉

2021-12-15 10:59 UTC, jf-viguier commented
> Are you ok to say that the module should have the same behavior with and without your PR? (without taking account performance issue ofc)

Not really: mr PR takes only the last orders (requested number * 50) containing the product. I guess it's more relevant because products change every day in a real ecommerce shop.
So, it's a breaking change I guess.

2022-02-28 11:45 UTC, saulaski requested changes

2022-02-28 11:45 UTC, saulaski commented on ps_crossselling.php
> +        ORDER BY date_add desc LIMIT ' . ((int) Configuration::get('CROSSSELLING_NBR')) * 50;
Would be a good idea to use alias to avoid any SQL conflict in the future:
```suggestion
        ORDER BY o.date_add desc LIMIT ' . ((int) Configuration::get('CROSSSELLING_NBR')) * 50;
```

2022-02-28 11:45 UTC, saulaski commented on ps_crossselling.php
> +        ORDER BY date_add desc LIMIT ' . ((int) Configuration::get('CROSSSELLING_NBR')) * 50;
IMHO pagination size should use a variable with a default value defined as class constant:
```
protected function getOrderProducts(array $productIds = [], int $size = self::ORDER_PRODUCTS_SIZE)
```
```suggestion
        ORDER BY date_add desc LIMIT ' . ((int) Configuration::get('CROSSSELLING_NBR')) * $size;
```

2022-02-28 11:59 UTC, jf-viguier commented
@Progi1984 waiting for something on this ?
@saulaski I've 3 validations, it's ok for me, feel free to open a new PR for your improvement.

2022-02-28 12:42 UTC, saulaski commented
> @Progi1984 waiting for something on this ? @saulaski I've 3 validations, it's ok for me, feel free to open a new PR for your improvement.

In my very humble opinion, avoiding a hard coded limitation is not really an improvement :)
Same for hard coded constants, which should at least get defined as class constants.

2022-03-14 08:15 UTC, Progi1984 commented
@jf-viguier Could you rebase your PR ? (and fix @saulaski feedbacks)

Furthermore, we are waiting for a relative issue to this PR.

2022-03-14 11:08 UTC, jf-viguier commented
Hey guys, You have merged a similar PR without any discussion here:
https://github.com/PrestaShop/ps_crossselling/pull/27

It's a simple  LIMIT 30

2022-03-14 11:19 UTC, jf-viguier commented
I've added add a class constant for limit factor and change order column to id_order instead of date_add according to https://github.com/PrestaShop/ps_crossselling/pull/27

#27 has no issue two, so I'll stick to it ;-)

2022-03-14 12:07 UTC, saulaski approved these changes

2022-03-14 14:11 UTC, PierreRambaud approved these changes

2022-03-30 14:44 UTC, Progi1984 commented
@PrestaShop/qa-functional As it targets the performance, do you think the QA can be done by dev ?

2022-04-01 08:37 UTC, hibatallahAouadni commented
> @PrestaShop/qa-functional As it targets the performance, do you think the QA can be done by dev ?

@Progi1984 Yes, I think so :wink:

2022-04-01 08:46 UTC, jf-viguier commented
@Progi1984 may I ask for your QA ?

2022-05-05 16:29 UTC, matks approved these changes
Code for me is OK and tested ✅ 

Apologies for the delay @jf-viguier we have a big focus on 8.0.0 feature freeze, that should be over soon!

2022-05-05 16:30 UTC, merged

2022-05-06 07:02 UTC, matks commented
By the way another similar PR https://github.com/PrestaShop/ps_crossselling/pull/27