Limit de $q_orders results
PrestaShop/ps_crossselling pull request #5
Opened 2019-11-20 10:19 UTC by djbuch

We limit this query to avoid having an IN query with thousands of unnecessary order ids.

I have multiplied the limit by 4 to minimize the case where products have been disabled.

But having hundreds of IDs in the order ID list or thousands or even hundred of thousands ID in this list (for big shops) make the whole difference between a query that is as few ms and a query that runs for seconds.

2020-09-04 14:58 UTC, Progi1984 approved these changes

2020-09-07 08:55 UTC, PierreRambaud requested changes
Is there a reason to use the ORDER BY RAND()?
Could you create an issue on the main repository to be sure the Product team agree about this improvement? :)

2020-09-07 10:17 UTC, matthieu-rolland reviewed
I agree with @PierreRambaud , you should probably create an issue here, explaining your problem, and link this issue to your PR.

Here's where to create your issue: https://github.com/PrestaShop/PrestaShop/issues/new?template=1_bug_report.md

Then it will be validated by Prestashop's product team 👍

2020-09-07 12:18 UTC, djbuch commented
Hello I created this issue here : https://github.com/PrestaShop/PrestaShop/issues/20874

I'm adding ORDER BY RAND() because of the ORDER BY RAND() present in the query for the products line 306.

If I don't add the ORDER BY RAND() in the first query it will always select the same orders to find cross sellings from.

2020-09-09 08:02 UTC, PierreRambaud commented on ps_crossselling.php
> +        AND od.product_id IN ('.implode(',', $productIds).') ORDER BY RAND() LIMIT '.(int)Configuration::get('CROSSSELLING_NBR')*4;
```suggestion
        AND od.product_id IN ('.implode(',', $productIds).') ORDER BY RAND() LIMIT ' . (int) Configuration::get('CROSSSELLING_NBR')*4;
```

2020-09-09 08:02 UTC, PierreRambaud approved these changes

2020-09-09 10:07 UTC, djbuch commented
Here you have also the pull request for the core : https://github.com/PrestaShop/PrestaShop/pull/20916

2020-09-09 12:06 UTC, matthieu-rolland approved these changes

2020-11-05 14:59 UTC, khouloudbelguith commented
Hi @djbuch,

Please resolve the Conflicting files.

Thanks!

2021-02-03 09:12 UTC, sarahdib commented
Hello

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to ask to re-open when it will be possible to fix the conflicting file

Thank you!

2021-02-03 09:12 UTC, closed without merging